### ISSUE TITLE
first problem

### ISSUE THREAD

**Issue by battlealanna** [hydro-lab/Pittsburgh-Water-Changes#1]
reprojecting the raster giving error:
```
> cover.proj<- projectRaster(cover,crs = sr)
Error in .local(.Object, ...) : 
```

**Comment by dmkahler** [comment]
I started debugging the code, so pull before you make any changes.

**Comment by dmkahler** [comment]
This was not successful in R.  The cutGeotiffs.py script works.  The initial problem that we were having in the python code was not the code, there was a overlapping loop in the watershed from streamstats.  I fixed the watershed and will upload the new one to Box.  Next week we will run the python code.
